const kanaRomajiTable = {
    'あ': ['a'], 
    'い': ['i'], 
    'う': ['u', 'wu', 'whu'], 
    'え': ['e'], 
    'お': ['o'], 
    'か': ['ka', 'ca'], 
    'き': ['ki'], 
    'く': ['ku', 'cu', 'qu'], 
    'け': ['ke'], 
    'こ': ['ko', 'co'], 
    'さ': ['sa'], 
    'し': ['si', 'shi'], 
    'す': ['su'], 
    'せ': ['se'], 
    'そ': ['so'], 
    'た': ['ta'], 
    'ち': ['ti', 'chi'], 
    'つ': ['tu', 'tsu'], 
    'て': ['te'], 
    'と': ['to'], 
    'な': ['na'], 
    'に': ['ni'], 
    'ぬ': ['nu'], 
    'ね': ['ne'], 
    'の': ['no'], 
    'は': ['ha'], 
    'ひ': ['hi'], 
    'ふ': ['hu', 'fu'], 
    'へ': ['he'], 
    'ほ': ['ho'], 
    'ま': ['ma'], 
    'み': ['mi'], 
    'む': ['mu'], 
    'め': ['me'], 
    'も': ['mo'], 
    'や': ['ya'], 
    'ゆ': ['yu'], 
    'よ': ['yo'], 
    'ら': ['ra'], 
    'り': ['ri'], 
    'る': ['ru'], 
    'れ': ['re'], 
    'ろ': ['ro'], 
    'わ': ['wa'], 
    'を': ['wo'], 
    'ん': ['nn'], 
    'っ': ['xtu', 'ltu'], 
    'ー': ['-'], 
    'ぁ': ['xa', 'la'], 
    'ぃ': ['xi', 'li'], 
    'ぅ': ['xu', 'lu'], 
    'ぇ': ['xe', 'le'], 
    'ぉ': ['xo', 'lo'], 
    'ゃ': ['xya', 'lya'], 
    'ゅ': ['xyu', 'lyu'], 
    'ょ': ['xyo', 'lyo'], 
    'ゎ': ['xwa', 'lwa'], 
    'が': ['ga'], 
    'ぎ': ['gi'], 
    'ぐ': ['gu'], 
    'げ': ['ge'], 
    'ご': ['go'], 
    'ざ': ['za'], 
    'じ': ['zi', 'ji'], 
    'ず': ['zu'], 
    'ぜ': ['ze'], 
    'ぞ': ['zo'], 
    'だ': ['da'], 
    'ぢ': ['di'], 
    'づ': ['du'], 
    'で': ['de'], 
    'ど': ['do'], 
    'ば': ['ba'], 
    'び': ['bi'], 
    'ぶ': ['bu'], 
    'べ': ['be'], 
    'ぼ': ['bo'], 
    'ぱ': ['pa'], 
    'ぴ': ['pi'], 
    'ぷ': ['pu'], 
    'ぺ': ['pe'], 
    'ぽ': ['po'], 
    'ふぁ': ['fa'], 
    'ふぃ': ['fi'], 
    'ふぇ': ['fe'], 
    'ふぉ': ['fo'], 
    'ヴぁ': ['va'], 
    'ヴぃ': ['vi'], 
    'ヴ': ['vu'], 
    'ヴぇ': ['ve'], 
    'ヴぉ': ['vo'], 
    'うぁ': ['wha'], 
    'うぃ': ['whi', 'wi'], 
    'うぇ': ['whe', 'we'], 
    'うぉ': ['who'], 
    'きゃ': ['kya'],    
    'きぃ': ['kyi'],    
    'きゃ': ['kya'], 
    'きゅ': ['kyu'], 
    'きぇ': ['kye'], 
    'きょ': ['kyo'], 
    'しゃ': ['sya', 'sha'], 
    'しぃ': ['syi'], 
    'しゅ': ['syu', 'shu'], 
    'しぇ': ['sye', 'she'], 
    'しょ': ['syo', 'sho'], 
    'ちゃ': ['tya'], 
    'ちぃ': ['tyi'], 
    'ちゅ': ['tyu'], 
    'ちぇ': ['tye'], 
    'ちょ': ['tyo'], 
    'ひゃ': ['hya'], 
    'ひぃ': ['hyi'], 
    'ひゅ': ['hyu'], 
    'ひぇ': ['hye'], 
    'ひょ': ['hyo'], 
    'ふぁ': ['fa'], 
    'ふぃ': ['fi'], 
    'ふぇ': ['fe'], 
    'ふぉ': ['fo'], 
    'ふゃ': ['fya'], 
    'ふぃ': ['fyi'], 
    'ふゅ': ['fyu'], 
    'ふぇ': ['fye'], 
    'ふょ': ['fyo'], 
    'みゃ': ['mya'], 
    'みぃ': ['myi'], 
    'みゅ': ['myu'], 
    'みぇ': ['mye'], 
    'みょ': ['myo'], 
    'りゃ': ['rya'], 
    'りぃ': ['ryi'], 
    'りゅ': ['ryu'], 
    'りぇ': ['rye'], 
    'りょ': ['ryo'], 
    'ぎゃ': ['gya'], 
    'ぎぃ': ['gyi'], 
    'ぎゅ': ['gyu'], 
    'ぎぇ': ['gye'], 
    'ぎょ': ['gyo'], 
    'じゃ': ['zya', 'jya', 'ja'], 
    'じぃ': ['zyi', 'jyi'], 
    'じゅ': ['zyu', 'jyu', 'ju'], 
    'じぇ': ['zye', 'jye', 'je'], 
    'じょ': ['zyo', 'jo', 'jo'], 
    'ぢゃ': ['dya'], 
    'ぢぃ': ['dyi'], 
    'ぢゅ': ['dyu'], 
    'ぢぇ': ['dye'], 
    'ぢょ': ['dyo'], 
    'びゃ': ['bya'], 
    'びぃ': ['byi'], 
    'びゅ': ['byu'], 
    'びぇ': ['bye'], 
    'びょ': ['byo'], 
    'ぴゃ': ['pya'], 
    'ぴぃ': ['pyi'], 
    'ぴゅ': ['pyu'], 
    'ぴぇ': ['pye'], 
    'ぴょ': ['pyo'], 
};

function convertRomaji(word) {
    const result = [];
    let cursor = 0;
    while(cursor < word.length) {
        const parts = [word.substr(cursor, 3), word.substr(cursor, 2), word.substr(cursor, 1)];
        for(let part of parts) {
            const romajis = kanaRomajiTable[part];
            if (romajis) {
                result.push(structuredClone(romajis));
                cursor += part.length;
                break;
            }
        }
    }
    return result;
}

console.log(convertRomaji('しんねん'));
console.log(convertRomaji('しんしゃ'));
console.log(convertRomaji('たっせい'));
console.log(convertRomaji('じっしゃ'));
console.log(convertRomaji('しゃちょう'));
console.log(convertRomaji('しゃしん'));
